### ISSUE TITLE
feat: close when marked as read

### ISSUE THREAD

**Issue by watthefak** [0x2E/fusion#13]
When I use the bottom float to mark an item as read, it would be nice to automatically close this item and go back to the main list.
Currently, I open an item, scroll to the end, mark read, then scroll to top and click on the "Unread" tab.

**Comment by 0x2E** [comment]
The swipe-back gesture in the system/browser works well. However, we do need an explicit back action button or alert.

Thanks for the feedback.

**Comment by watthefak** [comment]
I'm on a PC. Taking my hand off the mouse to press alt+arrow takes even longer than scrolling up to click "Unread".
