### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by gexiaosen** [0x2E/fusion#14]
1、Some RSS links are unique and only accessible at certain times, resulting in connection timeouts when added at other times. It is suggested to implement a feature for forced saving.
2、It is recommended to add a time selector to set the update frequency for each RSS link.
3、It is recommended to add support for the Chinese language.
Thank you.

**Comment by 0x2E** [comment]
Thanks for the suggestions.

> 1、Some RSS links are unique and only accessible at certain times, resulting in connection timeouts when added at other times. It is suggested to implement a feature for forced saving.

Why not just add it in that time window.

> 2、It is recommended to add a time selector to set the update frequency for each RSS link.

The current interval is set to [30 minutes](https://github.com/0x2E/fusion/blob/8a25ffa154ee48a07a5141d5122255a122a5ff6b/service/pull/pull.go#L16). We will refactor the polling mechanism to allow for various intervals per feed.

> 3、It is recommended to add support for the Chinese language.

Tracked in https://github.com/0x2E/fusion/issues/10

**Comment by 0x2E** [comment]
Tracked in #23 .
