### ISSUE TITLE
Feature Suggestion : Can logout

### ISSUE THREAD

**Issue by xavier-GitHub76** [0x2E/fusion#18]
Hello,

I don't find a button to logout.

**Comment by xavier-GitHub76** [comment]
Are there plans to be able to use fusion in multi-user mode ?

**Comment by 0x2E** [comment]
Hi.

> I don't find a button to logout.

Will add it soon.

> Are there plans to be able to use fusion in multi-user mode ?

No, and maybe never.

**Comment by 0x2E** [comment]
Included in https://github.com/0x2E/fusion/releases/tag/v0.8.7
