### ISSUE TITLE
Buttons not visible on smartphones

### ISSUE THREAD

**Issue by xavier-GitHub76** [0x2E/fusion#20]
Hello,

some buttons are visible when mouse hovering
![image](https://github.com/user-attachments/assets/0ad4fa75-22ce-436f-ac3c-e54e21867e95)

These buttons are not visible on smartphones

**Comment by 0x2E** [comment]
It works on all devices. However, on a mobile device, it's hard to perform a hover action. You can try pressing it for over 1 second. Unfortunately, this could also trigger the options of the mobile browser, which resembles a "right click," at the same time.
