### ISSUE TITLE
suggestion: listen on unix socket?

### ISSUE THREAD

**Issue by qingyiwebt** [0x2E/fusion#22]
Listen on a unix socket such as `/run/user-service/my-fusion.sock` so that we can proxy it in nginx like the following:
```nginx
# ...
location /my-fusion/ {
    proxy_pass http://my-fusion/;
}
# ...
upstream my-fusion {
    server unix:/run/user-service/my-fusion.sock;
}
```  
This can avoid listening on an IPv4/6 port, and have a better proxy performance.

**Comment by 0x2E** [comment]
Hi, Thanks for the suggestion.

Fusion will never hit the performance bottleneck in the common usage case. However, if you really need it, I'd recommend forking the project and modifying the [code](https://github.com/0x2E/fusion/blob/4f7db53bce2f8ea65f72287101201f9390f9f514/api/api.go#L126-L130) based on this [discussion](https://github.com/labstack/echo/discussions/1750).
