### ISSUE TITLE
[BUG] 升级到0.8.8版本docker部署报错

### ISSUE THREAD

**Issue by yalidabuda** [0x2E/fusion#27]
## Environments

- Version: 0.8.8
- OS: docker
- Device & Browser: 

## The Current Behavior

升级到0.8.8版本docker部署报错如下：

cannot find .env, skip

2024/09/03 00:58:34 /src/repo/repo.go:92 record not found
[1.196ms] [rows:0] SELECT * FROM `feeds` WHERE id = 1 AND `feeds`.`deleted_at` = 0 ORDER BY `feeds`.`id` LIMIT 1
panic: record not found

goroutine 1 [running]:
github.com/0x2e/fusion/repo.tableExist({0xc819e0, 0xc0001646c0})
	/src/repo/repo.go:97 +0x107
github.com/0x2e/fusion/repo.migrage.func1(0xc0002cc2d0)
	/src/repo/repo.go:37 +0x45
gorm.io/gorm.(*DB).Transaction(0xc0002cc0f0, 0xe94160, {0x0?, 0x0?, 0x0?})
	/go/pkg/mod/gorm.io/gorm@v1.25.11/finisher_api.go:651 +0x262
github.com/0x2e/fusion/repo.migrage()
	/src/repo/repo.go:35 +0x2c
github.com/0x2e/fusion/repo.Init()
	/src/repo/repo.go:27 +0xff
main.main()

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by yalidabuda** [comment]
> try this https://bit.ly/4e4zLlq select the desired compiler in the installer

这个链接无法打开

**Comment by 0x2E** [comment]
> > try this https://bit.ly/4e4zLlq select the desired compiler in the installer
> 
> 这个链接无法打开

Don't trust that.

**Comment by 0x2E** [comment]
Will fix it soon.

**Comment by 0x2E** [comment]
Hi. v0.8.9 fixed it.

**Comment by yalidabuda** [comment]
> Hi. v0.8.9 fixed it.

好的，v0.8.9确实可以正常使用了😁

**Comment by 0x2E** [comment]
Thanks for the feedback!
