### ISSUE TITLE
feat: support choosing group(s) when importing feeds

### ISSUE THREAD

**Issue by jwq2011** [0x2E/fusion#5]
For example, when I import RSS files, there are already relevant folders that have been properly classified. However, when using Fusion to import, they will still be discarded, resulting in all entries being in an unordered state. I need to create a new folder by myself. I hope to support the import of folders from the original RSS files. Thank you

**Comment by 0x2E** [comment]
Just append some context for myself:

- https://opml.org/spec2.opml#1629042482000

**Comment by 0x2E** [comment]
Hi @jwq2011 @superkuh @williballenthin . I've implemented this feature in #25 . However, ORM's auto-migration concerns me a lot. Could you help me test it on your database?

Here are the steps to test it:

1. Download the binary file from https://github.com/0x2E/fusion/releases/tag/v0.8.8-test .
2. Make a copy of your real database.
3. Run Fusion with the downloaded binary and the data copy.
4. Export the current OPML.
5. Delete some feeds and groups on the webpage.
6. Import the OPML file.

Please check:

1. Any crash or errors happened?
2. Will the deleted feeds and groups be recreated?

Thanks! :D
