### ISSUE TITLE
401 Password Error, 0.8.3 Error Reporting

### ISSUE THREAD

**Issue by knoop7** [0x2E/fusion#7]
**There is a problem with the latest 0.8.3 key checking logic, on 0.8.2 there is no error reported, the problem is that homeassistant as an add-on in the store leads to a password 401 error, I hope you can roll back the refactoring of this issue, as a big fan of RSS also feel that this aspect should be removed from verification of passwords**

h.go:117\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:674\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3142\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2044"}
{"level":"error","ts":"2024-07-13T12:35:40.279+0800","caller":"api/api.go:56","msg":"code=401, message=Wrong password","module":"api","uri":"/api/sessions","status":401,"stacktrace":"github.com/0x2e/fusion/api.Run.func1\n\t/src/api/api.go:56\ngithub.com/labstack/echo/v4/middleware.RequestLoggerConfig.ToMiddleware.func1.1\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/request_logger.go:381\ngithub.com/0x2e/fusion/api.Run.Recover.RecoverWithConfig.func4.1\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/recover.go:130\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP.func1\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:668\ngithub.com/0x2e/fusion/api.Run.RemoveTrailingSlash.RemoveTrailingSlashWithConfig.func7.1\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/middleware/slash.go:117\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.12.0/echo.go:674\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3142\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2044"}

**Comment by 0x2E** [comment]
Starting from version 0.8.3, the `.env` file is included in the release archive. Therefore, verify the password in your `.env`.

**Comment by knoop7** [comment]
Thanks! Just noticed

**Comment by 0x2E** [comment]
We've refactored the conf module. From v0.8.4, the .env file is no longer archived in releases.

Currently, all configuration items, except `PASSWORD`, have their own default values in the code. Therefore, you just need to modify the necessary items using your .env file or environment variables.

Please follow the [configuration](https://github.com/0x2E/fusion#configuration) section.
